#operadores de asignacion =,+=,-=,*=,/=,**=

# += OPERADOR DE LAS SUMAS 

num1= 5
# num = num + 4  ESTA EXPRESION REALIZA LA MISMA FUNCION SOLO QUE EXPRESADA DE DIFERENTE MANERA 
num1 += 4
print (num1 )

#OPERADOR DE LAS RESTAS

num = 8 
# num = num - 5   ESTA EXPRESION REALIZA LA MISMA FUNCION SOLO QUE EXPRESADA DE DIFERENTE MANERA 
num -= 5
print(num )

# OPERADOR DE LAS DIVISIONES 
num2 = 10
#num2 = num2 / 2  ESTA EXPRESION REALIZA LA MISMA FUNCION SOLO QUE EXPRESADA DE DIFERENTE MANERA 
num2 /= 2 
print(num2)

#OPERADOR DE LA MULTIPLICACIONES

num3 = 3 
# num3 = num3 * 4   ESTA EXPRESION REALIZA LA MISMA FUNCION SOLO QUE EXPRESADA DE DIFERENTE MANERA
num3 *= 4
print(num3)

#OPERADOR DE LA POTENCIA

num4 = 12 
# num4 = num4 ** 12
num4 **= 12
print(num4)
